import type { Metadata } from "next";
import { Lato } from "next/font/google";
import React, { useState } from "react";
import Header from "../components/header";
import "./globals.css";

const lato = Lato({
  subsets: ["latin"],
  display: "swap",
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: { locale: string };
}
export default function RootLayout({
  children,
  params: { locale },
}: Readonly<RootLayoutProps>) {

  return (
    <html lang={locale}>
      <body className={`${lato.className}`}>
        <div className="flex flex-col h-screen max-w mx-auto items-center text-white">
          <Header />
          <div className="w-full h-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
